<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
  </PropertyGroup>

  <ItemGroup>
    <None Include="wwwroot\images\alexandra-nosova-kly-z2c54b0-unsplash.jpg" />
    <None Include="wwwroot\images\flower-729514_640.jpg" />
    <None Include="wwwroot\images\rose-1732782_640.jpg" />
    <None Include="wwwroot\images\tulip-3360748_640.jpg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.1" PrivateAssets="all" />
  </ItemGroup>

</Project>
